### ISSUE TITLE
Create a file management in App

### ISSUE THREAD

**Issue by tmquang0209** [tmquang0209/Simulator#25]
- Display user's list file > select file > option menu will display (open, delete, move, copy, permission)
- Shared file list (the author is someone else, the user has access to the file)
- Unified opening and editing functions. If the user has edit permission => display full text and edit.

**Comment by ngtddat** [comment]
Quang oi cai file 'demo1_data.txt' noi dung no nhu nao the, toi chua ro lam

**Comment by lazane779** [comment]
dung english di cau

**Comment by tmquang0209** [comment]
> 
this is demo:
Author: tmq
Permission:
+ View: tmq1,tmq2,tmq3
+ Edit: tmq1,tmq2
+ Delete: tmq3
+ Rename: tmq1,tmq3

**Comment by ngtddat** [comment]
ok, got it

**Comment by lazane779** [comment]
remember you should change the dot sign into plus sign

**Comment by ngtddat** [comment]
danke, ich verstehe

**Comment by DatDangg** [comment]
Amazing file

**Comment by tmquang0209** [comment]
I updated the FileManager class, it returns error code instead of print error message. I see some problem in copy function, I will fix this in next commit.

**Comment by DatDangg** [comment]
Idk how can we use the "moveFile" function

**Comment by tmquang0209** [comment]
all files are saved at FileManager folder, with moveFile function, curentDir is subfolder of FileManager. Similar to this image, the currentDir of demo1.txt is tmq.
<img width="119" alt="image" src="https://github.com/tmquang0209/Simulator/assets/61152867/713434bb-9530-4067-8415-6b1e84faa5eb">

**Comment by tmquang0209** [comment]
if rename (successful file move, it will return msg code as 1, error as -2 and disallowed as -1)

**Comment by tmquang0209** [comment]
> all files are saved at FileManager folder, with moveFile function, curentDir is subfolder of FileManager. Similar to this image, the currentDir of demo1.txt is tmq. <img alt="image" width="119" src="https://user-images.githubusercontent.com/61152867/252374813-713434bb-9530-4067-8415-6b1e84faa5eb.png">

another example: folderdemo is a subfolder of tmq => currentDir = tmq/folderdemo
targetDir is the same way.

**Comment by DatDangg** [comment]
but i can't get info.username, it's empty :D

**Comment by tmquang0209** [comment]
changed private to protected?

**Comment by DatDangg** [comment]
Of course

**Comment by DatDangg** [comment]
oh, I solved the problem

**Comment by DatDangg** [comment]
I modified the functions. The "permissonFile" function is a little confusing to me; I don't get it. What must I do about the "shared file list" task? Not really properly understood.

**Comment by tmquang0209** [comment]
In this "permissionFile" function, User will assign permissions to other users, for example: userA assigns permission to edit and delete files for userB,...

**Comment by DatDangg** [comment]
I've finished the 1st assignment, but what about tasks 2 and 3? Could you describe it?

**Comment by tmquang0209** [comment]
what is this?

**Comment by DatDangg** [comment]
![image](https://github.com/tmquang0209/Simulator/assets/134087868/00985ec8-2b64-4fc0-abb0-914aa659ac72)

**Comment by tmquang0209** [comment]
- List of shared files (the author is someone else, the user has permission to access the file)
++ Create a function, read file was shared, Example: UserB has edit permission the file A.txt, it will display in share file list
- Unified opening and editing functions. If the user has edit permission => display full text and edit.
++ check access, if user has edit permission, call edit function. Otherwise, if you only have view permission, call the read function

**Comment by DatDangg** [comment]
I just uploaded the new code. What I know has been carried out. Send me a message if you need anything else. I will go to bed.
