### ISSUE TITLE
Check bug

### ISSUE THREAD

**Issue by tmquang0209** [tmquang0209/Simulator#29]
I just uploaded the draft code, everyone please pull back in 'draft' branch and check for errors, If there is any problem, comment here

**Comment by lazane779** [comment]
1. I just check the code so we need to include the <ctime> in characterHandling.cpp the code will run.
2. I've a question that why the function create user are placing at home function but not the login function?

**Comment by tmquang0209** [comment]
> 1. I just check the code so we need to include the  in characterHandling.cpp the code will run.
> 2. I've a question that why the function create user are placing at home function but not the login function?

1. Please test your environment, the code works well
2. Since only admins can create users

**Comment by DatDangg** [comment]
- I don't know if anyone suffers like me. It is necessary to #include <time.h> in "characterHandling.cpp"
- There is a problem when we do: Account info -> Update information -> Back. I can't press [back] to return to the "Home" 
- If there is a "Create account" in the "Account list" , can we remove the "Create User" in the "Home". 
- The error in the "Create account" function is that the full name cannot be filled, I fixed it by adding cin.ignore(); before getline(cin, fullname);
![image](https://github.com/tmquang0209/Simulator/assets/134087868/cc8b2eb9-d9f0-41ca-bf91-390b68a6bd31)
>>> Few mistakes in the "createAccount" function, I'll correct and re-upload.
>>> I will add [back] in the functions View, Edit, ... in the "File manager"

**Comment by tmquang0209** [comment]
1. Regarding the lack of libraries, you should manually add the missing library to the project, you can use #include<bits/stdc++.h> to import the entire library
2. Regarding issue 2, we need to remove the same element to return to the previous page
<img width="270" alt="image" src="https://github.com/tmquang0209/Simulator/assets/61152867/c9e17138-a2cb-460d-acde-29e9861b9afe">

**Comment by DatDangg** [comment]
One small question: I think we should create the folder after we create account, right?

**Comment by DatDangg** [comment]
I just edited and uploaded. There's a problem: after creating the user, we'll be back at "Home". At this point, when creating an account, it will have a little error. I'm not sure how to explain it, but the mouse (Idk how to read it) is in the "account type" line rather than the "full name" line.

**Comment by tmquang0209** [comment]
> One small question: I think we should create the folder after we create account, right?
yes, create folder after successful account creation.
>I just edited and uploaded. There's a problem: after creating the user, we'll be back at "Home". At this point, when creating an account, it will have a little error. I'm not sure how to explain it, but the mouse (Idk how to read it) is in the "account type" line rather than the "full name" line.
can you take a screenshot?

**Comment by tmquang0209** [comment]
> One small question: I think we should create the folder after we create account, right?

yes, create folder after successful account creation.

**Comment by tmquang0209** [comment]
> I just edited and uploaded. There's a problem: after creating the user, we'll be back at "Home". At this point, when creating an account, it will have a little error. I'm not sure how to explain it, but the mouse (Idk how to read it) is in the "account type" line rather than the "full name" line.

can you take a screenshot?

**Comment by DatDangg** [comment]
> > I just edited and uploaded. There's a problem: after creating the user, we'll be back at "Home". At this point, when creating an account, it will have a little error. I'm not sure how to explain it, but the mouse (Idk how to read it) is in the "account type" line rather than the "full name" line.
> 
> can you take a screenshot?

![image](https://github.com/tmquang0209/Simulator/assets/134087868/ccd08e29-d785-4877-a8bd-f1e87b0448f9)
Need to press Enter to continue

**Comment by DatDangg** [comment]
> > One small question: I think we should create the folder after we create account, right?
> 
> yes, create folder after successful account creation.

got it

**Comment by tmquang0209** [comment]
> > > I just edited and uploaded. There's a problem: after creating the user, we'll be back at "Home". At this point, when creating an account, it will have a little error. I'm not sure how to explain it, but the mouse (Idk how to read it) is in the "account type" line rather than the "full name" line.
> > 
> > 
> > can you take a screenshot?
> 
> ![image](https://user-images.githubusercontent.com/134087868/252833637-ccd08e29-d785-4877-a8bd-f1e87b0448f9.png) Need to press Enter to continue

I think we should ignore this error. It's not that important. We need optimized code for high performance

**Comment by DatDangg** [comment]
Should "File Manager" be updated? If you have permission, show the function. For instance, if you have the "delete" permission, the "delete" function will be display, otherwise it will be hidden

**Comment by DatDangg** [comment]
As for the report, Lâm said it was done. So what about slides

**Comment by tmquang0209** [comment]
> As for the report, Lâm said it was done. So what about slides

You do it, I think slides will summarize the report. Add video tutorials if needed.

> Should "File Manager" be updated? If you have permission, show the function. For instance, if you have the "delete" permission, the "delete" function will be display, otherwise it will be hidden

I will do it

**Comment by tmquang0209** [comment]
I just updated App.cpp. Please check this again

**Comment by DatDangg** [comment]
An idea, check it out. After "Create File" will create both ".txt" and "_data.txt". And the "_data.txt" file will automatically add author (with author name == username), and permission lines. Hmmm, okay?
